apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-demo
  namespace: s3-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: s3-demo
  template:
    metadata:
      labels:
        app: s3-demo
    spec:
      serviceAccountName: s3-demo-sa
      containers:
      - name: application-container
        # The script will look for this image line and dynamically replace everything after the colon
        image: manivannancsmca/s3-demo:PLACEHOLDER 
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "test"
          - name: AWS_REGION
            value: "ap-south-1"
